print("Enter your age please:",end=" ")
age= input()
print("Enter your height:",end=" ")
height=input()
print("How much do you weigh?",end=" ")
weight=input()
print(f"So, you're {age} old, {height} tall and {weight} heavy")
